source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SamplePod_Example', :exclusive => true do
  pod 'SamplePod', :path => '../'
pod 'Alamofire'
end

target 'SamplePod_Tests', :exclusive => true do
  pod 'SamplePod', :path => '../'

  
end
